baseURL: https://www.r15cookie.com
languageCode: en-us
defaultContentLanguage: en
title: R15Cookie Blog 
copyright: "Steve Miller [BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/)"


theme: r15-papercss-hugo-theme
googleAnalytics: UA-65123306-1
disqusShortname: r15cookieblog

paginate: 5

privacy:
  disqus:
    disable: false

taxonomies:
  tag: tags

permalinks:
  post: /post/:filename/

imaging:
  quality: 99

params:
  description: A DevOps practitioner with an appreciation for robust architectures.
  homeMetaContent: A DevOps practitioner with an appreciation for robust architectures.
  tagline: A DevOps practitioner with an appreciation for robust architectures.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  navTitleLink: /
  mainSections: post
  #github_corner_url: "https://github.com/ssmiller25/r15cookieblog"
  gitlab_corner_url: "https://gitlab.com/ssmiller25/r15cookieblog"
  footer: true

menu:
  nav:
    - name: About
      url: /about/
      weight: 2
    - name: Info
      url: /info/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 5
#    - name: RSS
#      url: /index.xml
#      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 12
    startLevel: 2
