baseURL = "https://www.r15cookie.com/"
disablePathToLower = true
languageCode = "en-us"
title = "R15Cookie Blog"
theme = "kiera-ssmiller25"

paginate = 5


pygmentsCodeFences = true
disqusShortname = "r15cookieblog" #Disqus shortname

features = ["google-analytics","font-awesome"]


# Add Tag cloud
[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[author]
    name = "Steve Miller"       #Author name
    github = "ssmiller25"     #Github username
    gitlab = "ssmiller25"     #Gitlab username
    linkedin = "steve-miller-9936632"   #LinkedIn username
    facebook = ""   #Facebook username
    twitter = "scubbasteve25"    #Twitter username
    instagram = ""  #Instagram username

[params]
  mainSections = ["post"]
  # See http://tholman.com/github-corners/ for options
  # githubcorner = "https://www.github.com/ssmiller25/ssmiller.github.io"
    gitlabcorner = "https://gitlab.com/ssmiller25/r15cookieblog"
    tagline = "A DevOps practitioner with an appreciation for robust architectures."
    googleAnalyticsUserID = "UA-65123306-1" #Google Analytics ID

# Allow raw HTML

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true