baseURL = "https://www.r15cookie.com"
disablePathToLower = true
languageCode = "en-us"
title = "R15Cookie Blog"
theme = "kiera"

paginate = 5


pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "UA-65123306-1" #Google Analytics ID
features = ["google-analytics","font-awesome"]

# Add Tag cloud
[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[author]
    name = "Steve Miller"       #Author name
    github = "ssmiller25"     #Github username
    gitlab = "ssmiller25"     #Gitlab username
    linkedin = "steve-miller-9936632"   #LinkedIn username
    facebook = ""   #Facebook username
    twitter = "scubbasteve25"    #Twitter username
    instagram = ""  #Instagram username

[params]
    tagline = "There's always a cookie on the R15 resistor"
