apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: r15cookieblog-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: r15cookieblog
            port: 
              number: 80
        

